# Generated by Django 4.2.16 on 2024-11-30 08:48

from django.db import migrations, models
import django.db.models.deletion
import django.template.defaulttags


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_supportticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.template.defaulttags.now)),
                ('notes', models.TextField()),
                ('interaction_type', models.CharField(choices=[('Call', 'Call'), ('Email', 'Email'), ('Meeting', 'Meeting'), ('Other', 'Other')], max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='customer.customer_details')),
            ],
        ),
    ]
