# Generated by Django 4.2.16 on 2024-12-01 17:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customerinteraction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_details',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customeruserprofile'),
        ),
        migrations.AlterField(
            model_name='customerinteraction',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
