# Generated by Django 4.2.16 on 2024-12-01 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customer_details_user_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_details',
            old_name='user_profile',
            new_name='UserProfile',
        ),
    ]
