# Generated by Django 4.2.16 on 2024-12-01 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_customeruserprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeruserprofile',
            old_name='user',
            new_name='User',
        ),
    ]
