# Generated by Django 4.2.16 on 2024-12-01 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_rename_user_customeruserprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruserprofile',
            name='User',
        ),
    ]
