# Generated by Django 4.2.16 on 2024-12-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_remove_customeruserprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_details',
            name='UserProfile',
        ),
    ]
