# Generated by Django 4.2.16 on 2024-11-01 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='password1',
            new_name='password',
        ),
    ]
